#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook "apache2"
cookbook 'java', '~> 1.28.0'
cookbook "apt"
cookbook "git"
cookbook "build-essential"
cookbook 'elasticsearch', :git => 'https://github.com/elasticsearch/cookbook-elasticsearch'
cookbook 'logstash', '~> 0.9.2'
cookbook 'kibana', :git => 'https://github.com/realityforge/chef-kibana'