#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook "apache2"
cookbook 'java', '~> 1.28.0'
cookbook "apt"
cookbook "git"
cookbook "build-essential"
depends 'elasticsearch', '~> 0.3'
depends 'logstash', '~> 0.9'
        :git => 'https://github.com/elasticsearch/cookbook-elasticsearch'
#cookbook 'kibana', 
	#:git => 'https://github.com/realityforge/chef-kibana'

#cookbook 'elkstack', '= 0.1.1'


# cookbook 'chef-client'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
